---
title: 自定義異常
date: 2017-06-12 17:24:58
tags: [python]
categories: 工作問題
---
> 自定義異常
# 異常
##  try  except  
通常異常使用是
``` python
try:
	int('sss')
except Exception as e:
	print('這是一個簡單的異常,異常為:'+str(e))

output:這是一個簡單的異常,異常為:invalid literal for int() with base 10: 'sss'
```

## finally
升級版
``` python
try:
	int('sss')
except Exception as e:
	print('這是一個簡單的異常,異常為:'+str(e))
finally:
	print('這裡是最后')

output:這是一個簡單的異常,異常為:invalid literal for int() with base 10: 'sss'
output:這裡是最后
```
## try else 
沒有發生異常時觸發
``` python
try:
	int('1')
except Exception as e:
	print('這是一個簡單的異常,異常為:'+str(e))
else:
	print('沒有異常')
finally:
	print('這裡是最后')
	
output：1
output：沒有異常
output：這裡是最后
```
## raise 
返回一個異常
``` python
try:
	if 1:
	   raise EOFError()
except Exception as e:
	print('這是一個簡單的異常,異常為:'+str(e))
else:
	print('沒有異常')
finally:
	print('這裡是最后')
	
output：這是一個簡單的異常,異常為:
output：這裡是最后
```

## 自定義異常類
創建異常類
``` python
#繼承Exception類
class WeError(Exception):
	"""
	自定義異常
	"""
	def __init__(self,data):
		Exception.__init__(self,data) #初始化父類
		self.data = data
```
調用定義的異常類
``` python
try:
  if 1:
    raise WeError('出錯了')
except Exception as e:
  print(str(e))
finally:
  print('結束了')
	
output:出錯了
output:結束了
```


